name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0-alpha, v1.0.0, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Determine source branch
        id: branch
        run: |
          # Alpha/beta builds come from dev, stable builds come from main
          if [[ "${{ github.ref }}" == *"alpha"* ]] || [[ "${{ github.ref }}" == *"beta"* ]]; then
            echo "SOURCE_BRANCH=dev" >> $GITHUB_OUTPUT
            echo "Building alpha/beta release from dev branch"
          else
            echo "SOURCE_BRANCH=main" >> $GITHUB_OUTPUT
            echo "Building stable release from main branch"
          fi
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch.outputs.SOURCE_BRANCH }}
          fetch-depth: 0

      - name: Fetch tag annotations
        run: git fetch --tags --force
        shell: bash

      - name: Verify branch
        run: |
          echo "Building from branch: ${{ steps.branch.outputs.SOURCE_BRANCH }}"
          echo "Current HEAD: $(git rev-parse HEAD)"
          echo "Tag: ${{ github.ref }}"
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyinstaller pillow

      - name: Create icon.ico from PNG
        run: |
          python -c "from PIL import Image; img = Image.open('app/core/icon.png'); img.save('app/core/icon.ico', format='ICO', sizes=[(16,16), (32,32), (48,48), (64,64), (128,128), (256,256)])"

      - name: Build Sonorium.exe
        run: |
          cd app/windows/src
          pyinstaller --distpath .. --workpath ../build --clean Sonorium.spec

      - name: Build updater.exe
        run: |
          cd app/windows/src
          pyinstaller --distpath .. --workpath ../build --clean Updater.spec

      - name: Download Python embeddable
        run: |
          # Download Python 3.11 embeddable package (64-bit)
          $pythonUrl = "https://www.python.org/ftp/python/3.11.9/python-3.11.9-embed-amd64.zip"
          $pipUrl = "https://bootstrap.pypa.io/get-pip.py"

          # Create python directory
          New-Item -ItemType Directory -Force -Path "python_embed"

          # Download and extract Python embeddable
          Write-Host "Downloading Python embeddable..."
          Invoke-WebRequest -Uri $pythonUrl -OutFile "python_embed.zip"
          Expand-Archive -Path "python_embed.zip" -DestinationPath "python_embed" -Force
          Remove-Item "python_embed.zip"

          # Enable pip by modifying python311._pth
          Write-Host "Enabling pip in embedded Python..."
          $pthFile = "python_embed/python311._pth"
          $pthContent = Get-Content $pthFile
          $newContent = $pthContent -replace '#import site', 'import site'
          $newContent += "`nLib\site-packages"
          Set-Content -Path $pthFile -Value $newContent

          # Download and run get-pip.py
          Write-Host "Installing pip..."
          Invoke-WebRequest -Uri $pipUrl -OutFile "python_embed/get-pip.py"
          & "python_embed/python.exe" "python_embed/get-pip.py" --no-warn-script-location
          Remove-Item "python_embed/get-pip.py"
        shell: pwsh

      - name: Install core dependencies into embedded Python
        run: |
          Write-Host "Installing core dependencies..."
          & "python_embed/python.exe" -m pip install --no-warn-script-location -r app/core/requirements.txt

          Write-Host "Verifying pyatv installation..."
          & "python_embed/python.exe" -c "import pyatv; print(f'pyatv version: {pyatv.__version__}')"

          Write-Host "Installed packages:"
          & "python_embed/python.exe" -m pip list
        shell: pwsh

      - name: Create core.zip with embedded Python
        run: |
          Rename-Item -Path "python_embed" -NewName "python"
          Compress-Archive -Path "app/core", "app/themes", "python" -DestinationPath core.zip -Force

          Write-Host "core.zip created with embedded Python"
          $zipSize = (Get-Item "core.zip").Length / 1MB
          Write-Host "Size: $([math]::Round($zipSize, 2)) MB"
        shell: pwsh

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          # Determine if prerelease
          if [[ "$VERSION" == *"alpha"* ]] || [[ "$VERSION" == *"beta"* ]]; then
            echo "PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "PRERELEASE=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Get tag message
        id: get_changelog
        run: |
          TAG_MESSAGE=$(git tag -l --format='%(contents)' ${GITHUB_REF#refs/tags/})
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Gitea Release
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          PRERELEASE="${{ steps.get_version.outputs.PRERELEASE }}"
          CHANGELOG=$(cat << 'CHANGELOG_EOF'
          ${{ steps.get_changelog.outputs.CHANGELOG }}
          CHANGELOG_EOF
          )

          # Create release body
          BODY="${CHANGELOG}

          ---

          ### Downloads
          - **Sonorium.exe** - Standalone Windows launcher (portable, ~37 MB)
          - **core.zip** - Core files with embedded Python (~100+ MB)

          ### First-time setup
          1. Download Sonorium.exe to any folder
          2. Run it - the app will automatically download required files
          3. No Python installation required - everything is self-contained!

          ### Manual installation
          1. Download both files
          2. Extract core.zip to the same folder as Sonorium.exe
          3. Run Sonorium.exe"

          # Create release via Gitea API
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEATOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"${VERSION}\", \"name\": \"Sonorium ${VERSION}\", \"body\": $(echo "$BODY" | jq -Rs .), \"draft\": false, \"prerelease\": ${PRERELEASE}}" \
            "http://192.168.1.222:3000/api/v1/repos/Synthesis/sonorium/releases")

          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "Created release ID: $RELEASE_ID"

          # Upload assets
          echo "Uploading Sonorium.exe..."
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEATOKEN }}" \
            -F "attachment=@app/windows/Sonorium.exe" \
            "http://192.168.1.222:3000/api/v1/repos/Synthesis/sonorium/releases/${RELEASE_ID}/assets?name=Sonorium.exe"

          echo "Uploading updater.exe..."
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEATOKEN }}" \
            -F "attachment=@app/windows/updater.exe" \
            "http://192.168.1.222:3000/api/v1/repos/Synthesis/sonorium/releases/${RELEASE_ID}/assets?name=updater.exe"

          echo "Uploading core.zip..."
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEATOKEN }}" \
            -F "attachment=@core.zip" \
            "http://192.168.1.222:3000/api/v1/repos/Synthesis/sonorium/releases/${RELEASE_ID}/assets?name=core.zip"

          echo "Release created successfully!"
        shell: bash
